### ISSUE TITLE
Boneh–Lynn–Shacham is still unter protection of US patent.

### ISSUE THREAD

**Issue by xqyww123** [liuweiran900217/CloudCrypto#1]
The Boneh–Lynn–Shacham signature scheme is actually registered as the patent [US7587605B1](https://patents.google.com/patent/US7587605), by Microsoft. And the patent will be active to 2024.

How do you think about this issue?

**Comment by liuweiran900217** [comment]
Dear @xqyww123 : 
That is the reason why this project is open-sourced and free to use for academic (not industry). Personally, I think it is necessary to register a patent for an elegant scheme.
